<section class="py-5">
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-8 offset-2 py-5">
                <div style="border: 0"  class="card shadow">
                    <div class="card-body">
                        <h3>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS SITE.</h3>
                        <p>Welcome to the To <a href="<?php echo base_url(); ?>"><?php echo base_url(); ?></a>  website. These terms of service (“Terms”) apply to the Site, and all of its divisions, subsidiaries, and affiliate operated Internet sites which reference these Terms of service.</p>
                        <p>This Website Terms is entered into between you and Tormami , its <strong>past, present, or future parents, subsidiaries, affiliates, predecessors, assignees, successors, and their respective agents, employees, directors, officers, partners, and members (whether acting in their corporate or individual capacity) (hereinafter referred to as “Tomami”, “we” or “us”), with a principal place of business at Rolls Royce Cinema, Korle Woko Accra- Ghana.</strong> Notwithstanding any language in the Website Terms to the contrary, the Website Terms have the same effect as an agreement in writing and govern your use of this site and its content, your engagement of Tormami’s services, your request that To Sell It contact you about its services, and/or your participation in To Sell It’s sales / reward program and services.</p>
                        <p>Tormami.com is a web site (the “Site”) that hosts classified advertising and related content created and developed by third-party users. Your use of the Site, including all access, services and/or features, is governed by these Terms of Use and the Privacy Policy (collectively, “Terms”), and you should review both carefully. By using the Site in any way, you are agreeing to comply with these Terms.</p>
                        <p>The Site reserves the right to change the Terms at any time and for any reason. Updated versions of the Terms will be posted to the Site at Tormami and you should visit this page periodically to keep apprised of any changes. By continuing to use the Site after any such change, you accept and agree to the modified Terms. The Site reserves the right to modify or discontinue, temporarily or permanently, the Site, any site features, benefits (including without limitation blocking or terminating your Account), rules or conditions, all without notice, even though such changes may affect the way you use the Site. You agree that the Site will not be liable to you or any third-party for any modification or discontinuance of the Site.</p>
                        <h4>REGISTRATION</h4>
                        <p>Though registration is not compulsory to use the Service or access to the Site, if you choose to register, you must complete the registration process. If you choose to register, you must submit a valid e-mail address and select a username and password during the registration process and be at least 18 years of age. You are responsible for maintaining the confidentiality of your</p>
                        <p>username and password, and all uses of your account, whether or not you have authorized such use. You agree to notify Tormami immediately of any unauthorized use of your account.</p>
                        <p>To Sell It reserves the right to refuse the Service or access to the Site to any user, or to delete accounts created by users who appropriate the name, likeness, email address or other personally identifiable information of another individual.</p>
                        <h4>CONTENT</h4>
                        <p>You concur that all listings, messages, text, files, images, photos, video, audio or other materials (“Content”) posted on, transmitted through, or linked from the Site are the sole responsibility of the person or organization from whom such Content originated. You also understand that To Sell It does not control and is not responsible for Content made available through the Site, and that by using the Site, you may be exposed to content that is offensive, indecent, inaccurate, misleading or otherwise objectionable. Please see our Content Policies page for complete details.</p>
                        <p>Furthermore, the Site and Content made available through the Site may contain links to other web sites that are completely independent of Tormami. Tormami makes no representation or warranty as the accuracy, completeness or authenticity of the information contained on such web site. Under no circumstances will Tormami be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, linked or otherwise made available via the Site.</p>
                        <p>You Concur and agree that any uploading or posting will be at your sole risk and To Sell It shall not be responsible to you in any way. Further, Tormami does not provide any warranty as to your use of third-party content or software that you obtain from the Site. You are also fully responsible for any Content you post on the Site and to the consequences of any such Content. Although To Sell It does not claim ownership of Content that its users post, by posting Content to the Service, you automatically grant, and you represent and warrant that you have the right to grant, to Tormami an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license to use, copy, perform, display and distribute said Content and to prepare derivative works of, or incorporate into other works, said Content, and to grant and authorize sublicenses through multiple tiers of the foregoing. You also understand and agree that Tormami, in its sole discretion, may delete any Content for any reason.</p>
                        <h4>USE OF MATERIALS</h4>
                        <p>Any ads or messages that you post, transmit, or otherwise make available for viewing on public areas of the Site will be treated as non-confidential and non-proprietary to you. You understand and agree that any such ads and messages may be used by the Site or our affiliates, without review or approval by you, for any purpose whatsoever, and in any medium, including our print media, if any. You grant the Site (and our affiliates) the irrevocable right to use and/or edit your</p>
                        <p>ads and messages, without review or approval by you, for any purpose whatsoever, including, without limitation, reproduction, disclosure, transmission, publication, broadcast, posting, and advertising in any media in perpetuity without notice or compensation to you.</p>
                        <h4>USER CONDUCT</h4>
                        <p>You agree, undertake and confirm that your use of Tormami, shall be strictly governed by the following binding principles. Tormami provides the Website and the Materials for your individual, non-commercial use and solely for the purpose of advertising, carrying out shopping and individual transactions with the Website. Any other use of the Website or the Materials is rigorously prohibited. Without limitation, you agree to refrain from the following actions while using the Site:</p>
                        <p>1. Harassing, threatening, embarrassing or causing distress or discomfort upon another individual or entity or impersonating any other person or entity or otherwise restricting or inhibiting any other person from using or enjoying the Site;</p>
                        <p>2. Transmitting any information, data, text, files, links, software, chats, communication or other materials that is unlawful, false, misleading, harmful, threatening, abusive, invasive of another’s privacy, harassing, defamatory, vulgar, obscene, hateful or racially or otherwise objectionable, including without limitation material of any kind or nature that encourages conduct that could constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, provincial, national, or international law or regulation, or encourage the use of controlled substances;</p>
                        <p>3. Posting advertising or solicitation in categories that is not appropriate, or posting the same item or service in more than one category or more than once every 7 days, or posting the same ad in multiple cities on the Site;</p>
                        <p>4. (a) Posting adult content or explicit adult material unless: (i) such material is specifically permitted in designated adult categories and permitted under applicable federal, state, and local law; and (ii) you are at least 18 years of age or older and not considered to be a minor in your state of residence;
                        (b) Posting, anywhere on the Site, obscene or lewd and lascivious graphics or photographs which depict genitalia or actual or simulated sexual acts, as determined in the sole discretion of tosellit.com;
                        (c) Posting any solicitation directly or in “coded” fashion for any illegal service exchanging sexual favors for money or other valuable consideration;
                        (d) Posting any material on the Site that exploits minors in any way;
                        (e) Posting any material on the Site that in any way constitutes or assists in human trafficking.</p>
                        <p>5. Posting any ad for products or services, use or sale of which is prohibited by any law or regulation;</p>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>